import type { Metadata } from "next";
import {  Montserrat, Open_Sans, Roboto, Roboto_Condensed } from "next/font/google";
import "./globals.css";
import I18nProvider from "@/components/provider/i18nProvider";
import { InterfaceProvider } from "@/components/context/interface-context";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const robotoCondensed = Roboto_Condensed({
  variable: "--font-roboto-condensed",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ scrollbarWidth: 'none', msOverflowStyle: 'none' }}>
      <body
        
        className={`${montserrat.variable} ${openSans.variable} ${roboto.variable} ${robotoCondensed.variable} antialiased`}
      >
        <InterfaceProvider>
          <I18nProvider>{children}</I18nProvider>
        </InterfaceProvider>
      </body>
    </html>
  );
}